Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\uPy1.0\uPyCraft\uPyCraft_src\readWriteUart.py", line 129, in run
  File "C:\Python34\lib\site-packages\serial\serialutil.py", line 590, in inWaiting
  File "C:\Python34\lib\site-packages\serial\serialwin32.py", line 257, in in_waiting
serial.serialutil.SerialException: ClearCommError failed (PermissionError(13, '¾Ü¾ø·ÃÎÊ¡£', None, 5))
